---
name: Build and push docker images

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  caddy:
    if: 1 == 0
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            os: linux
            arch: amd64
            variant: ""
          - platform: linux/arm64
            os: linux
            arch: arm64
            variant: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Get latest release version
        id: caddy-version
        uses: actions/github-script@v6
        with:
          script: |
            return github.rest.repos.getLatestRelease({
              owner: 'caddyserver',
              repo: 'caddy',
            }).then(result => {
                return result.data.name
            })
          result-encoding: string

      - name: Print result
        run: echo "${{steps.caddy-version.outputs.result}}"

      - name: Set up Golang environment
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check Go version
        run: go version

      - name: Set up xcaddy
        run: |-
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy
        env:
          GOOS: ${{matrix.os}}
          GOARCH: ${{matrix.arch}}
          GOARM: ${{matrix.variant}}
        run: |-
          mkdir -p ./artifacts/binaries/${{matrix.platform}}
          xcaddy build ${{steps.caddy-version.outputs.result}} \
            --output ./artifacts/binaries/${{matrix.platform}}/caddy \
            --with github.com/caddy-dns/cloudflare \
            --with github.com/kirsch33/realip \
            --with github.com/lucaslorentz/caddy-docker-proxy/v2@latest \
            --with github.com/caddyserver/caddy/v2@latest

      - name: Set version
        id: version
        run: |
          chmod 700 ./artifacts/binaries/linux/{amd64,arm64}/caddy
          echo "{name}=$(./artifacts/binaries/linux/amd64/caddy version | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: artifacts
          path: artifacts

  docker:
    # needs: caddy
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Download artifact
        if: 1 == 0
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Download artifact
        # if: 1 == 0
        id: download-artifact
        uses: dawidd6/action-download-artifact@master
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if the artifact is from a different repo
          # Required, if the repo is private a Personal Access Token with `repo` scope is needed
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: docker-publish.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: ""
          # Optional, will get head commit SHA
          # pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
          # commit: 19e01750421a6e508d98c766748e471b31719f7b
          # Optional, will use the specified branch. Defaults to all branches
          # branch: main
          # Optional, defaults to all types
          # event: push
          # Optional, will use specified workflow run
          run_id: 4460134294
          # Optional, run number from the workflow
          # run_number: 34
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them into respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: artifacts
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          # path: artifacts
          # Optional, defaults to current repo
          repo: ${{ github.repository }}
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts: false
          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          search_artifacts: false
          # Optional, choose to skip unpacking the downloaded artifact(s)
          # default false
          skip_unpack: false
          # Optional, choose how to exit the action if no artifact is found
          # can be one of:
          #  "fail", "warn", "ignore"
          # default fail
          if_no_artifact_found: fail

      - name: Set version
        id: version
        run: |
          chmod 700 ./binaries/linux/{amd64,arm64}/caddy
          echo "{name}=$(./binaries/linux/amd64/caddy version | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Print result
        run: echo "${{steps.version.outputs.version}}"

      # - name: Setup QEMU
      #   uses: docker/setup-qemu-action@master
      #
      # - name: Setup Docker buildx
      #   uses: docker/setup-buildx-action@v2
      #
      # - name: Log into Docker registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{secrets.DOCKER_USERNAME}}
      #     password: ${{secrets.DOCKER_PASSWORD}}
      #
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v2
      #   with:
      #     images: qosmio/caddy-docker-proxy
      #
      # - name: Build and push docker image (linux)
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: Dockerfile-alpine
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: qosmio/caddy-docker-proxy:latest, qosmio/caddy-docker-proxy:${{ steps.version.outputs.version }}
      #     labels: ${{ steps.meta.outputs.labels }}
          # tags: ghcr.io/${{github.repository}}:latest
          # tags: .io/${{github.repository}}:latest

# - name: Push repository
#   uses: stefanzweifel/git-auto-commit-action@v4
#   with:
#     commit_message: Automatic build
#     branch: master
#     file_pattern: list-modules.txt
